### ISSUE TITLE
please migrate to the new Fedora translation platform

### ISSUE THREAD

**Issue by Jibec** [fujiwarat/ibus-input-pad#2]
Hello, the Fedora project migrates its translation platform to Weblate [1].

This tool directly interact with your git repository, and requires us to know:
* [mandatory] which branch is your development branch?
* [mandatory] have you merged latest translation from Zanata and locked the project?
* [info] Weblate will handle updates when pot file changes, don't edit po files for this [2]
* [optional] what is the license of translation? (please use a code from https://spdx.org/licenses/)
* [optional] do you have any announcement/warning you would like to display to the translators? (it will be displayed in Weblate)
* [optional] do you need us to activate any specific checks? (this is a setting per component [3])
* [optional] do you need us to automatically detect new translation files? (typical usecase: website translation with one translation file per page)

Please note:
* For github hosted projects, Weblate open pull request. For other project, you'll have to add a key to allow commits.
* In Weblate's vocable, one project is a group of component. Each component is a translation file. You can have many projects or many components or both.
* You can change your mind over time, just reach trans@lists.fedoraproject.org

[1] https://communityblog.fedoraproject.org/fedora-localization-platform-migrates-to-weblate/ 
[2] https://docs.weblate.org/en/latest/admin/continuous.html#avoiding-merge-conflicts
[3] https://docs.weblate.org/en/latest/user/checks.html#translation-checks

**Comment by fujiwarat** [comment]
Probably I think it's better to open the Fedora bugs for the Fedora maintainers instead of the upstream.

>    [mandatory] which branch is your development branch?

master

>    [mandatory] have you merged latest translation from Zanata and locked the project?

yes

>    [info] Weblate will handle updates when pot file changes, don't edit po files for this [2]
>    [optional] what is the license of translation? (please use a code from https://spdx.org/licenses/)

It should be same with the license in the ibus SPEC file in Fedora.

>    [optional] do you have any announcement/warning you would like to display to the translators? (it will be displayed in Weblate)

The comment lines for MSGID should be informed to translators.

>    [optional] do you need us to activate any specific checks? (this is a setting per component [3])

Hope not to change the header comments in each PO file while I reported the issue to Zanata but it's still not fixed.

>    [optional] do you need us to automatically detect new translation files? (typical usecase: website translation with one translation file per page)

No but the customizable option would be desireble.

**Comment by Jibec** [comment]
done: https://translate.stg.fedoraproject.org/projects/ibus-input-pad/
user fujiwarat was also added as admin of ibus-input-pad 

you may be interesting in activating one of the following checks:
https://docs.weblate.org/en/weblate-3.10/admin/checks.html#customizing-behavior

**Comment by Jibec** [comment]
the previous project still looks like to be translatable https://fedora.zanata.org/project/view/ibus-input-pad
could you please have a look and lock it?
